### ISSUE TITLE
Add option to display more blocks below the portal

### ISSUE THREAD

**Issue by mfnalex** [GorgeousOne/NetherView#32]
When you stand before a portal, the view only goes done one (or two?) blocks. It would be nice if there was a config option that controls how much blocks into the ground get rendered. I made another GIF for better understanding:

[GIF:](https://api.jeff-media.de/tmp/netherview-fr.gif)
![GIF:](https://api.jeff-media.de/tmp/netherview-fr.gif)

Once you updated the source here on GitHub I might also look if I could make a pull request for this if you're interested, this plugin is really awesome! I'm glad I found it by accident^^

**Comment by GorgeousOne** [comment]
I honestly didn’t expect anyone to use the plugin for portal‘s in this size mainly. As you can see the box for the portal view is already huge just due to the dimensions of the portal. That’s why I thought I’d be better if therefore the render distance at all sides would get reduced so the amount of blocks doesn’t get too big. I can understand that this is a bit unsatisfying though.

**Comment by mfnalex** [comment]
It's not a problem at all! I don't think a regular player will sneak to the edge to observe such things. If I was you, I wouldn't really care about that. I just thought I should mention this because on SpigotMC you wrote "for all vanilla sized portals" :)

**Comment by GorgeousOne** [comment]
Okay I made some changes to it in the v1.3.1 update
